name: "BMS Pace - Influx"
description: "Pace BMS Data to Influx 1.8"
version: "0.1dev"
slug: "bms_pace_influx"
url: "https://github.com/jpgnz/bmspace"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

uart: true
usb: true

options:
  connection_type: "IP"
  bms_ip: "10.0.0.161"
  bms_port: 5000
  bms_serial: "/dev/ttyUSB0"
  scan_interval: 5
  debug_output: 0
  force_pack_offset: 0
  zero_pad_number_cells: 2
  zero_pad_number_packs: 0
  influx_host: "localhost"
  influx_port: 8086
  influx_username: "localhost"
  influx_password: "localhost"
  influx_db: "localhost"
schema:
  connection_type: list(IP|Serial)
  bms_ip: str
  bms_port: int
  bms_serial: str
  scan_interval: int
  debug_output: int
  force_pack_offset: "int?"
  zero_pad_number_cells: "int?"
  zero_pad_number_packs: "int?"
  influx_host: str
  influx_port: int
  influx_username: str
  influx_password: str
  influx_db: str